FROM alpine:edge

ARG USERID 1000

RUN apk update
RUN apk add \
        make \
        g++ \
        mingw-w64-gcc \
        i686-mingw-w64-gcc \
        s6 \
        zig
RUN adduser -u ${USERID} -D user_${USERID}
ENTRYPOINT ["/src/buildtools/entrypoint"]
